kind: pipeline
type: docker
name: hello-world

steps:
- name: docker  
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: alsaheem/docker-hello-world-drone
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest
