global-variables:
  debian_image: &debian_image debian:7.11-slim
  environment: &default_environment
    HOST: postgres
    USER: postgres

kind: pipeline
type: docker
name: drone-git-deployer

steps:

  - name: test-drone-plugin-bash
    image: alsaheem/webhook
    settings:
      url: https://wallet-api-dev.yassir.io/api/v1/actuator/health
      method: GET

  - name: test-drone-plugin-python
    image: alsaheem/healthchecker # public docker image
    settings:
      health_url: https://wallet-healthcheck-dev.yassir.io/api/v1/actuator/health
      pass_num: 20

  - name: sample-step-echo
    image: debian:stable-slim
    commands:
      - echo "The world is just a big ball"
      - echo "It was empty, but now it's not"
  
  - name: alpine test
    image: alpine
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
    commands:
      - echo $DOCKER_USERNAME

  - name: get-drone-envs
    image: debian:stable-slim
    commands:
      - echo "The current branch is ${DRONE_BRANCH}"
      - echo "The current commit hash is ${DRONE_COMMIT_SHA}"
      - echo "The image tag is ${DRONE_BRANCH//\//-}-${DRONE_COMMIT_SHA:0:8}"

  - name: anchor test
    image: *debian_image
    environment:
      <<: *default_environment
    commands:
      - echo "The host is $${HOST}"
      - echo "The user is $${USER}"

  - name: docker-build-push  
    image: plugins/docker
    settings:
      # registry: docker.io
      repo: alsaheem/docker-hello-world-drone
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: 
        - latest
        - ${DRONE_COMMIT_SHA:0:8}